name: catholic_liturgy
description: A package to calculate the Catholic Liturgy for every date and obtain liturgy description in multiple languages.
version: 0.0.18
homepage: https://github.com/flavio20002/Catholic-Liturgy-Dart

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  enum_to_string: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  csv: ^6.0.0

flutter:
